### ISSUE TITLE
1.14 - 1.2.0 - Adding Curios after Backpacked removes slot and backpack in it. 

### ISSUE THREAD

**Issue by MisterShawn** [MrCrayfish/Backpacked#1]
I added a new mod which required Curios. Upon joining my server I noticed my backpack and the slot it was in was missing. I'm guessing Backpacked disables its' own slot when Curios is installed but fails to check if there is already a backpack inside it and move it the Curios slot.

**Comment by MrCrayfish** [comment]
Make sure you remove the backpack before you add Curios. This is not a bug
