### ISSUE TITLE
Customize backpack button and quark "sort container" button overlap making it difficult to customize the backpack.

### ISSUE THREAD

**Issue by JetpackRescue** [MrCrayfish/Backpacked#100]
1.16.5 backpacked 2.1.3
The customize button overlaps with the quark "sort container" button. At the very least an x offset for the backpack's buttons would be nice. Quark does not allow you to move the buttons, and they're no longer working on the 1.16.5 version so you're the only one that can make the button positioning compatible.
![2022-04-01_06 20 13](https://user-images.githubusercontent.com/49115565/161272182-6756b515-db6a-4e55-92a2-eb0f3306b94e.png)

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/Backpacked/commit/dbcd9bb3e359a4e9384b8d2899fc2ceff4e810c3
You'll have to change the alignment in the client config.
