### ISSUE TITLE
Incompatibility with tinkers construct (1.12.2)

### ISSUE THREAD

**Issue by Santrocho** [MrCrayfish/Backpacked#101]
For some reason when I'm playing with both mods I can't use tinker short bows, long bows  and crossbows

**Comment by MrCrayfish** [comment]
Unfortunately I no longer maintain the 1.12.2 version of the mod and won't be resolving any imcompatiblites. If you aren't, make sure you are using Baubles (https://www.curseforge.com/minecraft/mc-mods/baubles) for better compatibility.
