### ISSUE TITLE
Incompatibility with Inventorio 

### ISSUE THREAD

**Issue by ArrowGamez** [MrCrayfish/Backpacked#102]
I'm having an issue with a mod called Inventorio that changes the way the Inventory system works but whenever I put in Backpacked and I die it deletes everything from Inventorios Inventory, I have talked to the creator (lizard_ofoz) and he said the this seems to be an issue on your end, I'm not fully sure as to what is causing the issue and I wasn't sure if you might have any idea as to what or way to fix this issue. I hope that there is something I can do to resolve this as I love both of these mods but if there isn't I understand. Thank you for your time.

**Comment by MrCrayfish** [comment]
I recommend to install Curios API to resolve incompatibilies.

**Comment by ArrowGamez** [comment]
Thinking about it now, I should have tried that. But I did and the both mods work together now with no issue. Thank you for the help!
