### ISSUE TITLE
MC Forge 1.18.2 Server causing players to have "Locked" backpack unlocks

### ISSUE THREAD

**Issue by damondanerd** [MrCrayfish/Backpacked#106]
Some players on my server unlocked custom backpacks. For example, the honey jar backpack or the wanderer pack. We noticed that some players now have their unlocked backpacks "Locked" with no text underneath it to describe progress towards the unlock, even though they previously unlocked it.

**Comment by MrCrayfish** [comment]
Make sure you are using the latest version of the mod, this was an issue that has been resolved. Unlocked backpacks have not been lost, it's just a sync issue for clients.
