### ISSUE TITLE
Quark & Backpacked arrow moving inventory support

### ISSUE THREAD

**Issue by zachsai** [MrCrayfish/Backpacked#107]
Any way you could add support for the quark arrows for moving things in and out of inventories with the backpacked mod?
![image](https://user-images.githubusercontent.com/63996164/163652319-2c1f8b45-0060-4081-aac9-664bca3d97dc.png)
For them to appear in the backpacked gui

**Comment by MrCrayfish** [comment]
Quark has a config option so you can add support to any container. See the general config  and the options `allowedScreens` and `printScreenClassnames`

**Comment by MrCrayfish** [comment]
I may add native support in the mod but Quark does provide a way to add support already.

**Comment by zachsai** [comment]
> Quark has a config option so you can add support to any container. See the general config and the options `allowedScreens` and `printScreenClassnames`

I tried doing this, but no success. This is what I entered in the quark config, which came from the printScreenClassnames
![image](https://user-images.githubusercontent.com/63996164/163695678-89a4c435-c686-4802-b6f1-68cf27b47e40.png)

**Comment by zachsai** [comment]
Got it working, but new problem, they overlap:
![image](https://user-images.githubusercontent.com/63996164/163697039-1c92323a-a841-4d64-8238-ae0baa6601a8.png)

**Comment by MrCrayfish** [comment]
Check latest release. Added an option to change the alignment of buttons.
