### ISSUE TITLE
Two problems

### ISSUE THREAD

**Issue by TinyGiraffes** [MrCrayfish/Backpacked#11]
Hello, This mod uses the same slot as the camping mod and glitches Ancient warfare so the research block opens a non-inventory UI meaning you can't interact with it
![Capture](https://user-images.githubusercontent.com/59845388/77187961-e48a5400-6a9a-11ea-98f3-b0cff090c294.PNG)

**Comment by MrCrayfish** [comment]
Please install Curios API or Baubles alongside Backpacked if you're running into any problems.
