### ISSUE TITLE
[1.16.5] Sever Not Showing Backpacks

### ISSUE THREAD

**Issue by slave2midna** [MrCrayfish/Backpacked#111]
Running latest version of Backpacked for 1.16.5 on a mod pack server, and for some reason the server is not letting backpacks show up on backs? If you load the mod pack in single player, it shows fine! But on the server it will not show. Is there anything I should look at that might explain why that is?

**Comment by MrCrayfish** [comment]
Are you using a normal Forge server? Not a hybrid with bukkit integration.

**Comment by slave2midna** [comment]
So sorry! But thank you Mr. Crayfish for the response! I Love your mods!

It's a pure forge server, running forge 36.2.35

Some troubleshooting I did, was deleting all configs and reloading them on the server just to see if that's where the issue was, but no dice I'm afraid. I did this because it's only happening on the server - but if I log out of the server and log into a single player game using the same client - it shows up fine and functions normally. I figured it had to be something on the server config side-and since its a server I set up, I feel like it's something I've turned off or disabled somewhere without realizing it. Like in the world settings or something - I am using Curios API with this mod, in order to use the backpack slot from that mod-in case that helps at all.

**Comment by slave2midna** [comment]
I'd like to add, that I discovered that it appears to only be affecting the Server Owner/Op - myself. I noticed this morning I was able to see the backpacks of others on the server when I walked by them. It is only my backpack specifically that is not showing up as the OP/Server Admin.

**Comment by MrCrayfish** [comment]
I think I know what the problem is. In Curios, you have the ability to disable the visibilty of curio items (the backpack). If you open the Curio GUI, click the little button on the slot where the backpack would go.
![image](https://user-images.githubusercontent.com/4958241/170931278-492d525e-87fc-4896-8a1d-76f8cffb04a7.png)

**Comment by slave2midna** [comment]
....Oh. Wow. I don't know if that's what it was, but when I went to check it appeared to be fixed. Honestly, I'm under the belief this was the problem and I was just losing my mind. thank you so much, you can close this! Everything is fine-I've never had problems with your mods, they always work so smoothly!
