### ISSUE TITLE
Not displaying correctly.

### ISSUE THREAD

**Issue by ricardo-jn** [MrCrayfish/Backpacked#112]
I need help!
I'm playing with my Wife on a modded server; just her and me. We can both see the backpack when I'm wearing it. But neither of us see it if she's wearing it. We both have the same PC, the same configurations, the same shaders and texture packs. all equal.

We are using:
Minecraft 1.18.2
Forge 1.18.2 - 40.1.0
OptiFine_1.18.2_HD_U_H7
Mod Backpacked 2.1.6 - 1.18.2
And another 120 Mods more.

I repeat. if I have the backpack, we both see it; if she has the backpack, none of us see it.

**Comment by MrCrayfish** [comment]
Refer to this issue report. My best guess is you are using Curios API and turned off the visibility of the backpack: https://github.com/MrCrayfish/Backpacked/issues/111
