### ISSUE TITLE
Piglin Backpacked is re-locked (and it's forever)

### ISSUE THREAD

**Issue by MrXell** [MrCrayfish/Backpacked#117]
In my modded survival I'm dead in the nether with my Backpack (with the piglin-skin) and when I retake my stuff and change my backpack skin, the piglin one was locked... and the count of "nether biome explored" disappear...

**Comment by MrCrayfish** [comment]
What version of the mod are you using?

**Comment by MrXell** [comment]
2.1.2 (the latest version available in 1.18.1)

(Sorry, if it was fixed in a newer version... but if there's a way to get the backpack back, that would be great...)

**Comment by MrCrayfish** [comment]
Yeah, it is fixed in newer versions. Backpack should be available just by reloading your world.
