### ISSUE TITLE
Startup crash in Magma version 1.16.5

### ISSUE THREAD

**Issue by PabloGirol** [MrCrayfish/Backpacked#118]
Seems that It crashes while trying to load the world

Here is the crash log extracted from latest.log: https://pastebin.com/t4G41x5F

**Comment by PabloGirol** [comment]
Seems to be fixed when changing from Magma to mohist

**Comment by MrCrayfish** [comment]
I've reworked the Mixin to have better compatibility, it should hopefully work now.
