### ISSUE TITLE
[Suggestion] Pickpocket option for non-players only

### ISSUE THREAD

**Issue by MarioSMB** [MrCrayfish/Backpacked#119]
The pickpocketing mechanic seems fun with the wandering villagers, but we don't want players pickpocketing eachother! An option to only allow non-player pickpocketing would be amazing.

**Comment by MrCrayfish** [comment]
I've fixed the config option `pickpocketBackpacks` in the server config to work as it's described in the comment. https://github.com/MrCrayfish/Backpacked/commit/c2321272374f20399abd819fc85748c686d96ecb
