### ISSUE TITLE
( 1.15.2 )  Crash from clicking Backpacked in Modlist

### ISSUE THREAD

**Issue by quake513** [MrCrayfish/Backpacked#12]
clicked modlist button in the main menu, and then clicked backpacked mod button, game crashed.

Tried both Backpacked 1.4.0-1.15.2 and 1.4.1- 1.15.2. Same thing happened every time.
I am linking the crash log.
[Crash log](https://github.com/MrCrayfish/Backpacked/files/4483755/Crash.log)
[crash-2020-04-15_17.05.59-client.txt](https://github.com/MrCrayfish/Backpacked/files/4483756/crash-2020-04-15_17.05.59-client.txt)

**Comment by MrCrayfish** [comment]
Duplicate of https://github.com/MrCrayfish/Backpacked/issues/3
