### ISSUE TITLE
[Suggestion] Add config option to let backpack use Chest slot when Curios is installed

### ISSUE THREAD

**Issue by CrownJoker** [MrCrayfish/Backpacked#124]
Would it be possible to put in a config option that enables backpacks to still get installed in the vanilla chest armor slot even when curios is installed? Either allowing it in both slots or only in the chest would be fine, I liked the balance of a backpack preventing armor, but some other mods in my pack require Curios.

Thanks!

**Comment by MrCrayfish** [comment]
This option unfortunately can't exist for techincal reasons.

**Comment by CrownJoker** [comment]
Sorry to post in a closed thread, but would it be possible to just disable Curios integration all together?

**Comment by MrCrayfish** [comment]
Only way is to uninstall Curios API.

Just to explain lightly, the server and clients all need to operate on the same rules. If a client was able to change the slot the backpack is placed in, it won't be able to correctly function with the server as the server thinks the backpack should be in a different slot.
