### ISSUE TITLE
Backpack only show first row

### ISSUE THREAD

**Issue by Lily221199** [MrCrayfish/Backpacked#133]
Also with just showing first row, when i opened it today, all the rest of the rows got thrown out on the ground, I have the latest mod for backpacked and also Curios Api latest one for my profile/game :(

![backpack](https://user-images.githubusercontent.com/63256675/210668521-92b1f08f-7852-4ebf-abf8-6b699de79cc9.JPG)

**Comment by MrCrayfish** [comment]
Are you using a modpack? Something (not my mod) replaced or changed the config. Configs aren't handled by my mod, and it's very unlikely it just randomly reset since it wouldn't only affect only my mod.

**Comment by bazinga181188** [comment]
We have the same problem. First it works fine with 4 rows i guess , after some time we just had one row left... how can i change the config file? its a class file.. Help would be nice becuse one row is just lame ^^ thx

**Comment by FusionU** [comment]
I too have this issue.  I'm running BMC3, but no other mods.  Its only showing the first row.
-after confirmation from MrCrayfish on it not being a bug, i edited config/backpacked-common.toml to
        #The amount of slot rows in the backpack inventory.
	#Range: 1 ~ 7
	backpackInventorySize = 5

works great, love this mod.

**Comment by MrCrayfish** [comment]
Apparently BMC3 Forge v10.5 changed the size. Not a bug.
