### ISSUE TITLE
Config of mod is reverted to mod default 

### ISSUE THREAD

**Issue by iMex6K** [MrCrayfish/Backpacked#136]
Hey, 

just like the issue I had with the mod "Chunk-Pregenerator" the config file of this mod is also reset incorrectly by forge. 

Every few restarts we have a backpack on the server with only one row because this is set as default in the mod and the config is reset to it.

backpackInventorySize = 1

[Thread-0/WARN] [net.minecraftforge.fml.config.ConfigFileTypeHandler/CONFIG]: Configuration file /home/mch/multicraft/servers/server240349/config/backpacked-common.toml is not correct. Correcting

Minecraft 1.19.2
Mod version 2.1.10
no Notepad++
File edited when server was offline

Errors from my side have already all been excluded. After all, it is only a change of a number from 3 to 1. 
The problem already occurred after the installation when we suddenly had only one row in the backpack after a restart. 

The creator of Chunk-Pregenerator released a patch for this very promptly and switched to a different config system. 
https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/issues/19

**Comment by iMex6K** [comment]
Night Config Fixes has a fix for this now after an Update. 
https://github.com/Fuzss/nightconfigfixes#workaround-2-apply-default-config-values-from-defaultconfigs

**Comment by MrCrayfish** [comment]
As mentioned above
