### ISSUE TITLE
[Feature Request]optional to use curios slot or backpack slot or both

### ISSUE THREAD

**Issue by ColaLiao** [MrCrayfish/Backpacked#138]
i play with skill cloak mod, but backpack slot will gone with curios mod,

so i can only chose cloak or backpack, i hope i can use both of them.

i hope to have a way to use curios slot or backpack slot or both

**Comment by MrCrayfish** [comment]
Backpacked uses the back slot from Curios API when it is installed. The backpack slot is not gone.
