### ISSUE TITLE
backpackInventorySize can't exceed 7; backpackInventorySizeColumns can't exceed 13

### ISSUE THREAD

**Issue by SplendidAlakey** [MrCrayfish/Backpacked#139]
**MC** 1.19.2
**Fabric** Loader 0.14.18 + API 0.76.0
**Backpacked** 2.2.0

To reproduce:

1. Set `backpackInventorySize` to 8 or above in the config
2. Launch the game
3. Check your config, it's been replaced by the default value of 1

This is not the same as #136, as not the whole config is reset, but rather just this option.

If it's not a bug, but an expected limitation, then I propose to add it in the comment, e.g. `#The amount of slot rows in the backpack inventory. Can't be more than 7.`. Same for `backpackInventorySizeColumns`, ~~if it also has a limit (I'm not sure, as it can go beyond the vanilla 9 just fine)~~ as it also has a limit of 13.

Logs: https://gist.github.com/SplendidAlakey/f8d5853c6405388f6defaa08464b17af

**Comment by MrCrayfish** [comment]
This is intended behaviour. If a config property is invalid, it will be reset to it's default value. The reason it is limited to 7 is simply due to 8 rows or above not fitting on the screen.
