### ISSUE TITLE
Shift Clicking Backpack From Shelf Deletes Items In Trinkets Back Slot

### ISSUE THREAD

**Issue by brotazoa** [MrCrayfish/Backpacked#146]
Backpacked v2.2.0
Trinkets v3.4.2

Shift clicking a backpack shelf with a backpack present will move the backpack to the trinkets back slot even if another item already occupies that slot, causing the previous item to be deleted.

**Comment by MrCrayfish** [comment]
Thanks for the report. Fixed in https://github.com/MrCrayfish/Backpacked/commit/7b9ae1f314e7bc0b151c4e8c3c8d0183a023f343
