### ISSUE TITLE
Backpack can store Crates from Charm for additional storage.

### ISSUE THREAD

**Issue by SpiderKolo** [MrCrayfish/Backpacked#15]
Charm is a mod which introduces a lot of small things to the game.
One of the things is a Crate - a block which can store up to 9 stacks of items.
Here is an empty crate:
![image](https://user-images.githubusercontent.com/62638498/82161921-fa50a580-98a0-11ea-99b6-7262bf0c8dab.png)
And here are two identical Crates with random modded block inside of it:
![image](https://user-images.githubusercontent.com/62638498/82161951-32f07f00-98a1-11ea-9baa-ac77c4ce7048.png)
Crate itself doesn't allow Shulker Boxes inside of itself, nor Shulkerboxes allow Crates....
But Crates can be but into Backpacks, and Backpacks into Crates creating an infinite storage cappability:
![image](https://user-images.githubusercontent.com/62638498/82162008-92e72580-98a1-11ea-979e-8048a94dab2a.png)
Just like there!

I guess you can already see an issue and I don't have to explain it, right?

**Comment by MrCrayfish** [comment]
There is nothing I can do! This issue has existed in every single mod that has added any sort of storage through an item. It has existed since the very start of modding.
