### ISSUE TITLE
[1.16.5] Backpack Duplication when Right Clicking from Curios Inventory

### ISSUE THREAD

**Issue by Sazuzaki** [MrCrayfish/Backpacked#152]
Just un-equip a backpack by right clicking it from your curios equipment.

**Comment by MrCrayfish** [comment]
Right clicked, no duplication. Please provide more details about the steps to reproduce and ensure you are not in creative.

**Comment by MrCrayfish** [comment]
Reopen the issue if it still exists. And please provide more details and steps to reproduce.
