### ISSUE TITLE
[FABRIC] Rendering issues in multiplayer

### ISSUE THREAD

**Issue by realzguy** [MrCrayfish/Backpacked#156]
Backpack slot not visible on players back and inventory slot is the missing texture placeholder.

I am playing multiplayer with only 2 people using [ESSENTAIL Mod](https://www.curseforge.com/minecraft/mc-mods/essential-mod)

**Comment by realzguy** [comment]
nevermind i didnt have trinkets

**Comment by retropele** [comment]
I had this same problem, thank you @realzguy. For some reason, Prism Launcher didn't pull Trinkets as a dependency for me with the Fabric version, so maybe there's something wrong with the way it's listed?

**Comment by MrCrayfish** [comment]
It's optional, so that's probably why it didn't pull it.

**Comment by retropele** [comment]
> It's optional, so that's probably why it didn't pull it.

Thanks for your response. :) Do you know if the missing texture could be resolved without adding Trinkets then?
