### ISSUE TITLE
1.16.1 Unhidden backpack

### ISSUE THREAD

**Issue by Ibirtem** [MrCrayfish/Backpacked#17]
Can't hide backpack in Curios slots.
Installed mods:
Backpack
Curios 
Cosmetic Armor Reworked (But how i remember, in 1.16.1 Curios have they own hide buttons)

**Comment by MrCrayfish** [comment]
???????????????

**Comment by Ibirtem** [comment]
I meen hide from my back? Bcz when equipped Elytra (or other bodyarmor) it's look awful????
![image](https://user-images.githubusercontent.com/54157950/88696820-660a8680-d10c-11ea-830b-4fa47ecf9c81.png)
![image](https://user-images.githubusercontent.com/54157950/88696894-80446480-d10c-11ea-8bd5-650903e360a5.png)
![image](https://user-images.githubusercontent.com/54157950/88696914-876b7280-d10c-11ea-9477-b92d8518b998.png)
