### ISSUE TITLE
Open Backpack keybind isn't configurable

### ISSUE THREAD

**Issue by mosharky** [MrCrayfish/Backpacked#178]
MC v1.20.1
Forge v47.1.3
Backpacked v2.2.5

It's getting registered, but its not configurable at all. It doesn't show up in the keybinds menu so its just stuck on B

**Comment by mosharky** [comment]
I've tested this with Forge v47.2.4 *and* with just Backpacked/Framework on their own as well; no other mods. There's no configurable keybind.

**Comment by Its-Just-Luci** [comment]
I'm also having this issue...

**Comment by BigPhobos** [comment]
vouch, the keybind is missing for me as well

**Comment by IdrisQe** [comment]
Yeah I'm experiencing this issue too. I assume it's still accessible in a config file? If not then maybe if you manually add the expected line to your controls file? Haven't tried either yet.

**Comment by Sto3IV** [comment]
Manually addint option in keyconfig did not solve the issue.

**Comment by IdrisQe** [comment]
And the client config file doesn't have any keybinding options either, so that's a bust...
I guess we're just stuck using the B key until this is  fixed.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/Backpacked/commit/fff4f5c46e3cef207bedb217d372e66e8296c88b
