### ISSUE TITLE
Fabric 1.20.1 Backpacked/Frameworks error causing game crash

### ISSUE THREAD

**Issue by CasualJeremy** [MrCrayfish/Backpacked#180]
Every time I leave a single player world or server using the mod my game crashes leaving me with this error

[ERROR](https://mclo.gs/hSyQkyL): java.lang.IllegalStateException: Config property is not linked yet

**Comment by twenty41** [comment]
Also having this under the same circumstances- Fabric 1.20.1, with EVERYTHING up to date. Also tried going back 1 version of Backpacked and Frameworks and the crash is still present
[crash-2023-11-24_19.10.27-client.txt](https://github.com/MrCrayfish/Backpacked/files/13462615/crash-2023-11-24_19.10.27-client.txt)

**Comment by twenty41** [comment]
Also happening when disconnecting from a server. Will be super annoying for users of my pack, pls help!

100% is caused by either Backpacked for Framework. Removing both fixed it, sadly switching to an inferior backpack mod
