### ISSUE TITLE
Backpack Shelf

### ISSUE THREAD

**Issue by MinecartCopper** [MrCrayfish/Backpacked#190]
Crafted a backpack shelf from this mod today and when I click the shelf with a backpack from inmis in my hand, it "deleted" the backpack from inmis that was in the trinket slot that had all my precious stuff in... real bummer... so put an empty backpack in the trinket slot and tried clicking the backpack shelf with an empty hand and again the backpack was removed/deleted from the trinket slot. Any way to figure out if it is possible to get that backpack back?

And now I know, don't try to make different mods be friends lol

**Comment by cmplstofB** [comment]
This may be a separate issue, but I'll write it here for now.

When an item is equipped off-hand, Right-clicking (or Shift + Right-clicking) to the Backpack Shelf does nothing. I think this is a bug.

**Comment by MrCrayfish** [comment]
Thanks for the report. This has been fixed in 3c67e4891c6fbc99bbcbf93e5fb40f9c2a0d06e2
