### ISSUE TITLE
backpack simply doesn't load/ not visible. Yet is still functional.    Using all the mods from Pokehaan Craft 2 with some added QOL Mods.

### ISSUE THREAD

**Issue by SerIousFaceOP** [MrCrayfish/Backpacked#197]
![336d4a4dfc3cf67e9332f9dbe4b7d3d7](https://github.com/MrCrayfish/Backpacked/assets/64708103/ec2ea44f-a909-4966-b371-ac8909b4e0ae)
![f0976c631d5541c0eec1b4a647899df0](https://github.com/MrCrayfish/Backpacked/assets/64708103/8efcb3ce-0105-4ada-bf20-cb69c8e64d80)

**Comment by MrCrayfish** [comment]
Are you using Curios API? Make sure you haven't toggled the visibility button on the slot.

**Comment by SerIousFaceOP** [comment]
sadly, I've already tried the basics. I looked around in configs and logs and couldn't see any line of text that would 'clearly' state interference with the backpack textures or models. I guess I'll just deal with it. Not game breaking just a little annoying. Thanks for your time anyways!
