### ISSUE TITLE
Immediate Crash on 1.12.2 - trying to load before baubles?

### ISSUE THREAD

**Issue by estradus** [MrCrayfish/Backpacked#2]
So!  Love the looks of this mod, looks like exactly what I wanted, but it crashes on the constructed stage of startup for my pack, after like, 5 seconds.
Minecraft 1.12.2, forge 14.23.5.2847.  Baubles 1.12-1.5.2, backpacked 1.3.0-1.12
Based on what I can tell from the log, it recognized that baubles was loaded and tried to call on baubles specific code before the baubles code had constructed?  But that's just a guess.

https://cdn.discordapp.com/attachments/460312917313847299/668139592574173214/2020-01-18-2.log.gz

**Comment by MrCrayfish** [comment]
This is hard for me to test. Are you able to run this version to see if this fixes the issue?
https://drive.google.com/file/d/14nfteK01KNu9dkgnRKjyAWZlz0mRDj5_/view?usp=sharing
or
https://drive.google.com/file/d/1aa_H3u7SlUm9CnRcSBjUXUose2YjRxYU/view?usp=sharing

**Comment by estradus** [comment]
Okay, I'm finally getting an opportunity to test things but wont be able to give a full report until the end of the night - but the first file is, at least, loading.

**Comment by estradus** [comment]
First file works great, that is, the backpacked-1.3.1-1.12.2.jar file.

**Comment by MrCrayfish** [comment]
Does the second file work too?

**Comment by estradus** [comment]
I'll take a look later today, I was juggling a lot of events last night.

**Comment by estradus** [comment]
The second file loads fine and also seems operative in-game.

**Comment by MrCrayfish** [comment]
Thanks for testing. I've released a new version 1.4.2
