### ISSUE TITLE
Pickpocketing configuration?

### ISSUE THREAD

**Issue by camilochys** [MrCrayfish/Backpacked#200]
I don't see any Pickpocketing configuration on the client, server or mods tab. I am using Fabric 1.20.1. Thanks for help.

**Comment by Bebrich** [comment]
![image](https://github.com/user-attachments/assets/d45f94f4-b045-4153-a60f-e77c88f4961b)
Its done with the server config thingie

**Comment by MrCrayfish** [comment]
Pickpocketing is found in the server config. On 3.0.0-beta and above versions, you should find it under `backpacked-server.toml` in your normal config folder.
