### ISSUE TITLE
Shelf deleting other back slot items

### ISSUE THREAD

**Issue by MrYORS** [MrCrayfish/Backpacked#203]
It seems that if you have another item in the back slot and you right click on the backpack shelf, the item in your back slot will be deleted. 
This happened to me using a satchel from the scout mod and right clicking on the backpack shelf. 

edit: everything inside the backslot backpack or satchel will be also deleted
edit2: this was on fabric version 1.20.1-3.0.0-beta.2

**Comment by muppetenergy** [comment]
oh god, I just discovered this is the case with the quark oddities backpack, too. 
1.20.1

**Comment by MrCrayfish** [comment]
Thanks for the report. This has been fixed in https://github.com/MrCrayfish/Backpacked/commit/3c67e4891c6fbc99bbcbf93e5fb40f9c2a0d06e2 and you should expect a patch released soon
