### ISSUE TITLE
Mixin error crash caused by captureDrops function upon loading on Neoforge version 20.6.115

### ISSUE THREAD

**Issue by seymourimadeit** [MrCrayfish/Backpacked#206]
Mod list:

Backpacked version: 1.20.6-3.0.0-beta.5
Curios version: 8.0.0-beta.6+1.20.6
Framework version: 1.20.6-0.8.13

Crash report: https://pastebin.com/2LrTWybe

**Comment by MrCrayfish** [comment]
Thanks for the report. I wasn't able to reproduce, but I have pushed a potential fix in beta.6 which will be released soon.
