### ISSUE TITLE
Backpack is invisible (1.20.1 forge)

### ISSUE THREAD

**Issue by vinnyg0621** [MrCrayfish/Backpacked#208]
![2024-06-19_23 42 41](https://github.com/MrCrayfish/Backpacked/assets/57818441/9d8c4f6b-e38d-4cab-b91a-e2dd779100b1)
![2024-06-19_23 42 48](https://github.com/MrCrayfish/Backpacked/assets/57818441/336f9f40-7c34-4a54-a4c0-975ae668c13e)
![2024-06-19_23 42 58](https://github.com/MrCrayfish/Backpacked/assets/57818441/fd3990a6-164f-4cb6-8daf-e6f44a3a0f3c)
![2024-06-19_23 43 08](https://github.com/MrCrayfish/Backpacked/assets/57818441/bad21628-bc98-4e02-9ec1-a8c3f67d1e2d)

**Comment by stubkan** [comment]
Same issue here.  Using BetterMC BMC4 modpack

I notice that if I toggle the model to another one in Backpack Customization - then bam! its visible, all model variants are visible.

Until I take it off, and put it back on again - then it is invisible once more.

**Comment by vinnyg0621** [comment]
yep, when i toggle another one in customization, it is visible!

**Comment by MrCrayfish** [comment]
Thanks for the report. Fix in c537da87541f8529ab78e9c4326fcefef56b214c
