### ISSUE TITLE
Crafting Recipe not working

### ISSUE THREAD

**Issue by Pumkindeer346** [MrCrayfish/Backpacked#209]
The recipe shows up in jei but I doesn't work when i try to craft it

**Comment by MiguelRipe** [comment]
Me too. Here's a video to the behavior issue 
![image](https://github.com/MrCrayfish/Backpacked/assets/68668561/9038feda-8602-47dc-9eb0-f9a13e21b390)

**Comment by MrCrayfish** [comment]
It's a bug in BetterMC
