### ISSUE TITLE
Change The Backpack To be equipped in Curious Elytra's back slot.

### ISSUE THREAD

**Issue by morrisback** [MrCrayfish/Backpacked#23]
Change The Backpack To be equipped in Curious Elytra's back slot.
Insead of Having an sepearate slot for the same postition.

**Comment by ak1dd** [comment]
Please do retain the ability to use the mod as it is without Curios.  I like to remove additional dependencies and one thing I really like about backpacked is I have less mods/libraries to update.

**Comment by MrCrayfish** [comment]
This was changed to the back slot a while ago. Closing now. @ak1dd I won't be making the mod require Curios, only optional.
