### ISSUE TITLE
Backpack slot doesn't accept the backpack making it so you can't use it 1.16.3

### ISSUE THREAD

**Issue by TwoThiccBoi** [MrCrayfish/Backpacked#25]

**Comment by dr3ams** [comment]
Same here. Any solutions?

**Comment by D0CTOR-ZED** [comment]
Just wanted to mention something I noticed while trying to troubleshoot this issue for a pack.  There is some mod interaction between Backpacked and Industrial Foregoing related to their infinity_backpack.  Disabling their pack also prevents the backpacked pack from being inserted into it's slot.  Specifically, config/industrialforegoing/modules.toml [modules.tools.infinity_backpack] set to false breaks backpacked.

**Comment by MrCrayfish** [comment]
I'm going to need more information. Mod is working perfectly fine, regardless if Curois API is installed.
Seems to be https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/961 causing the issue.

![2021-01-19_13 50 20](https://user-images.githubusercontent.com/4958241/104983769-589bdc80-5a5d-11eb-9e5c-ead54baa3ca7.png)

![2021-01-19_13 54 52](https://user-images.githubusercontent.com/4958241/104984041-ea0b4e80-5a5d-11eb-8291-f6139173ad2e.png)

**Comment by D0CTOR-ZED** [comment]
More info (sorry for the delay): https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/961

**Comment by MrCrayfish** [comment]
This has been fixed in Industrial Foregoing, so assuming this will won't be an issue anymore.
