### ISSUE TITLE
[1.12.2] Item Duplication interaction with Oversized Item In Storage Area

### ISSUE THREAD

**Issue by KittenRaee** [MrCrayfish/Backpacked#27]
OISA forces inventories to adhere to TerraFirmaCraft item size limits by forcing max size of acceptable item.
When larger than allowed item is inserted into the backpack, item pops out of the inventory (expected behaviour), but also leaves the copy of the item in the backpack.
![2020-10-23_02 52 40](https://user-images.githubusercontent.com/23376922/96944350-e4dc4900-14da-11eb-910d-edf9a7ec17c0.png)
![2020-10-23_02 52 43](https://user-images.githubusercontent.com/23376922/96944354-e60d7600-14da-11eb-88eb-89732bb0f191.png)
![2020-10-23_02 52 48](https://user-images.githubusercontent.com/23376922/96944355-e6a60c80-14da-11eb-9473-32ea27e6d918.png)
![2020-10-23_02 54 04](https://user-images.githubusercontent.com/23376922/96944453-181ed800-14db-11eb-9344-2507d1832ad7.png)

**Comment by MrCrayfish** [comment]
I've discussed this issue further on https://github.com/DoubleDoorDevelopment/OversizedItemInStorageArea/issues/17 and not an issue with my mod.
