### ISSUE TITLE
Placing a backpack inside itself voids the pack and its contents

### ISSUE THREAD

**Issue by fretboardfreak** [MrCrayfish/Backpacked#28]
As a test I tried to put a backpack inside another backpack.  Things seem to work fine if I place backpack A inside of backpack B.

However, if I open the GUI for backpack A and move backpack A inside itself and close the GUI then the backpack and contents voided.

It might be a good idea to consider not allowing nested backpacks (that seems very over powered) or to at least not allow a backpack to be placed inside itself.

**Comment by MrCrayfish** [comment]
You can't nest them though... also it's impossible to move a backpack inside itself because it's a custom slot that's inaccessible when you open up the backpack GUI. Sounds to me that you're talking about a different mod.

**Comment by MrCrayfish** [comment]
This in the GUI of the backpack.
![](https://i.imgur.com/oqRBJ8Z.png)

**Comment by MrCrayfish** [comment]
Stale issue. Backpacks have and always been exempt from moving into themselves.
