### ISSUE TITLE
Feature Request: Use name of renamed backpack as title in GUI window

### ISSUE THREAD

**Issue by fretboardfreak** [MrCrayfish/Backpacked#29]
I sometimes like to have more than one backpack on me at a time. I find it convenient to rename the backpacks so that I have an idea what I have placed inside them.

When I open the GUI for a renamed backpack the Title of the GUI window just says Backpack.  It would be nice if the GUI Title could use the name of the backpack to give an indication of which backpack I am looking in at the moment.

Thanks and keep up the good work :+1:

**Comment by MrCrayfish** [comment]
Added in https://github.com/MrCrayfish/Backpacked/commit/cfd888daa195e4ff8344dcd581f4b10aa9ebb3ff
