### ISSUE TITLE
Backpack keybind triggers for non-backpacks

### ISSUE THREAD

**Issue by ChloeDawn** [MrCrayfish/Backpacked#34]
**Mod version:** 1.7.0

Equipping [an elytra](https://www.curseforge.com/minecraft/mc-mods/curious-elytra) or any other Curio back item* causes Backpacked to trigger the backpack opening sound.
###### **Tested with Industrial Foregoing's Infinity Backpack*
---
![Recording of backpack opening sound being triggered (with subtitles)](https://thumbs.gfycat.com/WellmadeScrawnyAsiaticlesserfreshwaterclam-max-14mb.gif)

---
I believe this bug may also be the reason I cannot open the Infinity Backpack when both Backpacked's and Industrial Foregoing's keybinds are bound to `B` - currently Backpacked's opening sound plays and no GUI opens.

**Comment by MrCrayfish** [comment]
Thanks for the report. I find it funny how the GIF is not really helpful in this scenario as it's a sound issue 😂
You can rebind the backpack key in the controls (it's under Inventory category).

**Comment by ChloeDawn** [comment]
I enabled subtitles to show the sound ^^

**Comment by MrCrayfish** [comment]
This should be fixed. I am assuming you are pressing B when the elytra is equiped?

**Comment by ChloeDawn** [comment]
Yes, it is fixed now! I was pointing out that the GIF was still helpful heh
