### ISSUE TITLE
Backpack chanching colors randomly [1.16.5]

### ISSUE THREAD

**Issue by rafaelkai** [MrCrayfish/Backpacked#37]
Here's my lastest log: 

[latest.log](https://github.com/MrCrayfish/Backpacked/files/6042706/latest.log)

**Comment by verrofy** [comment]
This needs to be fixed. Replying to get this boosted.

**Comment by MrCrayfish** [comment]
Update to the latest version...

**Comment by VerroFied** [comment]
This did not fix :(
