### ISSUE TITLE
Crash when loading mods (invalid dist DEDICATED_SERVER)

### ISSUE THREAD

**Issue by stanlexgreenson** [MrCrayfish/Backpacked#39]
Minecraft 1.16.5
Forge 36.0.42
backpacked-1.8.0-1.16.3.jar
[crash-2021-03-02_05.44.23-fml.txt](https://github.com/MrCrayfish/Backpacked/files/6067713/crash-2021-03-02_05.44.23-fml.txt)

**Comment by niftybottle** [comment]
Also having this issue consistently, ironically enough on my dedicated server. Reverting back to Backpacked 1.7.1 fixed the crash with no other changes.

**Comment by MrCrayfish** [comment]
Update to 1.8.1

**Comment by dannydjdk** [comment]
1.8.1 is only flagged for 1.16.3 on curseforge, so it's not appearing as an option in the app for 1.16.4-5 packs.

**Comment by MrCrayfish** [comment]
Updated!
