### ISSUE TITLE
[Suggestion] Make backpack inventory shared

### ISSUE THREAD

**Issue by MarioSMB** [MrCrayfish/Backpacked#43]
Backpacks add an amazing dynamic to the game, allowing one to store extra items in a visible backpack and even keep items on death! However, there is an aspect that seems a tad overpowered; one can make as many backpacks as they want and carry around a lot of additional inventories, effectively turning them into early-game shulker boxes.  
Perhaps it would make more sense for balance, given the persistent nature of backpacks, to have them all share a single inventory, similar to ender chests. That way any backpack you open would have the same contents.

**Comment by MrCrayfish** [comment]
It's sort of too late to implement something like that, since it would break all existing backpacks. It's a good suggestion though
