### ISSUE TITLE
Backpack colors flickering

### ISSUE THREAD

**Issue by verrofy** [MrCrayfish/Backpacked#44]
There was an issue about this that was closed but not fixed. Updating the mod does nothing.
In the gif below (Sorry it stutters at one part, but you can still clearly see the issue), the backpack flickers with and without shaders.
I also tested this without optifine installed btw

[**Imgur Link**](https://imgur.com/EutHRYa)

**Comment by MrCrayfish** [comment]
Which version are you using?

**Comment by verrofy** [comment]
Version 1.8.1 for 1.16

**Comment by MrCrayfish** [comment]
Going to assume Optifine changes the blending. I'll see what I can do

**Comment by verrofy** [comment]
Also quick note, this doesnt happen with the Backpacker backpacks. Only the backpacked one.

**Comment by unmoving-javi** [comment]
Having this issue without Optifine, so it's not just that.

**Comment by vtenfys** [comment]
This also occurs for me on Minecraft 1.16.5 and Forge 36.1.0, with and without Optifine

**Comment by MrCrayfish** [comment]
Can you try this version of the mod? I haven't been able to reproduce the issue, hoping you guys can test this. Make sure to unzip as the jar file is inside.
[backpacker-1.2.3-1.16.3.zip](https://github.com/MrCrayfish/Backpacked/files/6204220/backpacker-1.2.3-1.16.3.zip)

**Comment by vtenfys** [comment]
Thanks - this appears to have fixed the issue, yes!

**Comment by MrCrayfish** [comment]
Perfect! Closing issue now. Patch will be released properly soon
