### ISSUE TITLE
Does not support newer versions of curios API, even though it requires them

### ISSUE THREAD

**Issue by RobertHDPotatoes** [MrCrayfish/Backpacked#48]
Game crashes upon loading, with error message "Mod backpacked only supports curios 4.0.1.0 or above. Currently, curios is 1.16.5-4.0.5.1". This happens with slightly older versions of backpacked/curios as well, as I've tried several combinations of various versions of both mods. No combination works. Only started happening once I update from 1.16.4 to 1.16.5.

Minecraft Version: 1.16.5
Forge Version: 36.1.12
Curios version: curios-forge-1.16.5-4.0.5.1
Backpacked Version: 1.9.0-1.16.3

Crash Log: https://pastebin.com/f5g838zF

Latest Log: https://pastebin.com/CpYnX0mu

**Comment by ocram9** [comment]
This is because of a forge update, specfically this merge: MinecraftForge/MinecraftForge#7710

Downgrading to forge 31.1.9 is a temporary fix.

**Comment by MrCrayfish** [comment]
As mentioned, downgrade your Forge version to 1.16.5-36.1.9

**Comment by MrCrayfish** [comment]
Should be able to use Forge 36.1.10 and above now if using version 1.9.1 of Backpacked
