### ISSUE TITLE
Enhancement: Allow 'Backpacker' backpacks to be opened without being worn

### ISSUE THREAD

**Issue by ratkinsonuk** [MrCrayfish/Backpacked#52]
I'm using the largest backpack from the Backpacker extension, but also want the functionality of the Ender Backpack to allow me to transfer items back to base when out mining.

Is it possible to allow backpacks in the hotbar to be opened using right-click, rather than having to be worn?

Thanks, Rat.

**Comment by MrCrayfish** [comment]
No as that's how the mod is designed
