### ISSUE TITLE
backpacked-1.4.3-1.12.2.jar shows up as 1.4.2 in mod menu

### ISSUE THREAD

**Issue by markygnlg** [MrCrayfish/Backpacked#53]
I'd imagine that it's not worth updating to a new version for this but I thought I'd mention it just the same. Although:

- mcmod.info has: "version": "1.4.3"
- MANIFEST.MF has: Implementation-Version: 1.4.3-1.12.2

Screenshot:
![@1-backpacked 143-142](https://user-images.githubusercontent.com/62978705/120948861-4d361d00-c782-11eb-8563-72b51d9e838d.png)

**Comment by markygnlg** [comment]
Just out of curiosity, I'm not a programmer but is it caused by [Reference.java](https://github.com/MrCrayfish/Backpacked/blob/1.12.X/src/main/java/com/mrcrayfish/backpacked/Reference.java) ?

Please feel free to close this issue. Thanks for your great mods too!!

**Comment by MrCrayfish** [comment]
Closing due to discontinued version
