### ISSUE TITLE
1.10.1-1.16.3.jar Config File failed to load

### ISSUE THREAD

**Issue by TTvCow** [MrCrayfish/Backpacked#55]
Crash Report
[crash-2021-08-02_11.47.07-server.txt](https://github.com/MrCrayfish/Backpacked/files/6919095/crash-2021-08-02_11.47.07-server.txt)

When I delete the backpacked mod my world works and I can move around and do shit in the world but as soon as I add it back in it doesn't work. Are there some known compatibility issues with certain mods or code libraries?

**Comment by MrCrayfish** [comment]
Corrupted file. Delete the config file from the server-config folder.
