### ISSUE TITLE
Blacklist is not working

### ISSUE THREAD

**Issue by SaveTheJohnDoe** [MrCrayfish/Backpacked#57]
Added immersive engineering crates to the blacklisted item in the serverconfig

`#Common configuration settings
[common]
	#A list of items that are not allowed inside a backpack. Note: It is recommended to ban items that have an inventory as this will create large NBT data and potentially crash the server!
	bannedItems = ["<immersiveengineering:crate>"]`

But I can still put IE crates inside my backpack. Log states:

`[13:26:31] [Server thread/WARN]: Configuration file C:\Users\damie\curseforge\minecraft\Instances\Immersive Engineering 1.16.5\saves\New World (4)\serverconfig\backpacked-server.toml is not correct. Correcting`

I've tried with other syntax (eg without the quote marks) but it crashes instead so I reckon I've got the correct NBT tag syntax?

![image](https://user-images.githubusercontent.com/76874735/142728136-8eca150c-29c5-4203-b5c5-610279905beb.png)

**Comment by MrCrayfish** [comment]
Not a bug.
`bannedItems = ["immersiveengineering:crate"]` is the correct syntax.
