### ISSUE TITLE
Game Crash on Start up

### ISSUE THREAD

**Issue by Jorgee9001** [MrCrayfish/Backpacked#59]
Minecraft 1.16.5
Forge: 36.2.22

Game crashes on Start-up. No crash report is given. Attached is latest log file.

[latest.log](https://github.com/MrCrayfish/Backpacked/files/7799484/latest.log)

**Comment by SKrystianS** [comment]
i have the same problem,
Minecraft 1.16.5
Forge: 36.2.20

Hope this helps!

[latest.log](https://github.com/MrCrayfish/Backpacked/files/7799495/latest.log)

**Comment by MrCrayfish** [comment]
Fixed. Check new version in Discord
