### ISSUE TITLE
Game Launch Crashing

### ISSUE THREAD

**Issue by ghost** [MrCrayfish/Backpacked#60]
Whenever I load into a game, the launcher crashes before the mods are fully loaded in. Once that happens, it sends you back to the Minecraft screen and says that an unexpected issue has happened but doesn't show a crash report. I hope you can fix this so I can use this mod in my modpacks.

**Comment by MrCrayfish** [comment]
Send your game logs and the crash log. Telling me it crashed tells me nothing.

**Comment by MrCrayfish** [comment]
Fixed. Check new version in Discord

**Comment by ghost** [comment]
Thanks!
