### ISSUE TITLE
[Bug?] Default backpacks can be unlocked 

### ISSUE THREAD

**Issue by gaussandhisgun** [MrCrayfish/Backpacked#61]
"If someone gave me a penny each time I unlocked Default backpack, i would have two pennys. Which isn't a lot, but it's weird that it happened twice"

Basically, you can /unlockbackpack any of those two default backpacks, but only once. Weird.

**Comment by MrCrayfish** [comment]
Basically the two default backpacks are unlocked but not registered in the player data that they are unlocked. Not going to worry about about preventing this.
