### ISSUE TITLE
[Bug] "Hacked" backpacks dont save between singleplayer world restarts

### ISSUE THREAD

**Issue by gaussandhisgun** [MrCrayfish/Backpacked#62]
So I just got two backpacks, Trash Can with usual method and Rocket with /unlockbackpack, then I restarted my game and Rocket did not save as unlocked.

**Comment by gaussandhisgun** [comment]
Version: 2.0 public beta from that discord channel

**Comment by MrCrayfish** [comment]
Can't seem to reproduce.
