### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by smolinacadena** [MrCrayfish/Backpacked#65]
Hi @MrCrayfish 

Please check the following crash report, I just updated to backpacked 2.0.0 and I can't start the game. Side fact, the server with the Backpacked 2.0.0 mod installed starts without issue

[crash-2022-01-07_16.16.21-client.txt](https://github.com/MrCrayfish/Backpacked/files/7831411/crash-2022-01-07_16.16.21-client.txt)

**Comment by smolinacadena** [comment]
The modpack I'm using is this [one](https://www.curseforge.com/minecraft/modpacks/primatilandia) on version 1.0.7

**Comment by Nebula240** [comment]
Can confirm that happens on a dev version of The Cube Reborn too, seems to be a mixin conflict

**Comment by MrCrayfish** [comment]
Remove Backpacker, it's not compatible at this time with the latest update.
