### ISSUE TITLE
[Bug] Ineffective Multiplayer Settings?

### ISSUE THREAD

**Issue by AzumaMagica** [MrCrayfish/Backpacked#66]
Hey there!

It appears that changing the available option in backpacked-common.toml doesn't seem to have an affect on the mod in multiplayer. I tested both the inventory size and 'drop on death' settings and neither seem to function.

Changes to server configurations in backpacked-server.toml _do_ seem to work, but the options in backpacked-common.toml don't seem to exist in the server configuration.

I'm using the Configured mod to commit these changes, and while they don't seem to affect anything, the settings _do_ save; returning to the .toml shows that the changes were retained.

I can't find any documentation about how there might be another method or means to alter the backpacked size settings, so I can only assume that this is a bug.

**Comment by MrCrayfish** [comment]
You have to change the common config on the server, not the client, if you want to change the backpack size. Players do not individually get to choose their backpack size.

**Comment by AzumaMagica** [comment]
OK! Thank you.
