### ISSUE TITLE
[Suggestion] New Backpack Model

### ISSUE THREAD

**Issue by Matthysse** [MrCrayfish/Backpacked#69]
Hello!
I would love to see this type of bag as backpack skin (see image). I know it's not technically a backpack, but it still can technically contain items, and wouldn't clash with the elytras or the cape, it looks like an adventurer's bag, so why not getting it by going in all major structures that exist (so it's different from the advancement for all biomes)
Here I quickly made an example:
![unknown](https://user-images.githubusercontent.com/32510957/149936856-2ebab66b-383e-4ce9-8021-a1c1bcf1a6be.png)

**Comment by MrCrayfish** [comment]
Cool suggestion but it just not a design that would work. I have a standard design template that I use to make sure that the models I have designed display correctly on the player, customisation screen, and upcoming shelves. I would have to make a huge  expect for a design like this to work and it's not worth it.
