### ISSUE TITLE
Crash clicking on mod in mods menu

### ISSUE THREAD

**Issue by Dminty87** [MrCrayfish/Backpacked#7]
[crash-2020-01-29_18.20.57-client.txt](https://github.com/MrCrayfish/Backpacked/files/4131866/crash-2020-01-29_18.20.57-client.txt)

Minecraft said:  The game crashed whilst mouseclicked event handler
Error: java.lang.ArrayIndexOutOfBoundsException: 0

**Comment by MrCrayfish** [comment]
Duplicate of #3
