### ISSUE TITLE
[1.18.1] Progress towards unlocking backpack variants does not persist across death

### ISSUE THREAD

**Issue by Not-February** [MrCrayfish/Backpacked#70]
It took me a little while to pin down death as the reason for it resetting - for what it is worth, the backpack *does* drop when I die in my setup, and I'm noticing the loss in progress when I put it back on again after retrieving it.

**Comment by MrCrayfish** [comment]
Thanks. I'll get a fix out asap. If you were close to unlocking a backpack, you can use the command `/unlockbackpack`

**Comment by MrCrayfish** [comment]
Should work fine now in 2.0.3
