### ISSUE TITLE
Spice of Life: Carrot Edition incompatibility.

### ISSUE THREAD

**Issue by antauriprime** [MrCrayfish/Backpacked#71]
When both **Spice of Life: Carrot Edition** and **Backpacked** are present the Player can't respawn after dying.
Respawn button does nothing. The only way to respawn is to disable one or the other.

Demo:

https://user-images.githubusercontent.com/30935221/151409114-42f85198-d639-4dc9-8233-50714ebac6c1.mp4

**Comment by MrCrayfish** [comment]
Thanks for the report. This was an issue in my mod.

**Comment by juliand665** [comment]
Glad you found the issue! (and before I even got around to checking that email lol)

I went ahead and closed it on our end too :)
