### ISSUE TITLE
Mohist Crashes 

### ISSUE THREAD

**Issue by VovelPunch** [MrCrayfish/Backpacked#73]
Backpacked Version: 2.1.0-1.16.
[latest.log](https://github.com/MrCrayfish/Backpacked/files/8008856/latest.log)
[debug.log](https://github.com/MrCrayfish/Backpacked/files/8008857/debug.log)

**Comment by MrCrayfish** [comment]
Should be fixed in https://github.com/MrCrayfish/Backpacked/commit/3032ceabec38e9b34a657733fc25154700266a4b
