### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by SkullDiamond** [MrCrayfish/Backpacked#76]
I try the last update and sever crash on startup

crash.log: https://pastebin.com/SQa4YeD2

**Comment by SkullDiamond** [comment]
I still have the same issue whit backpacked-2.1.1-1.16.5.jar on server
crash.log: https://pastebin.com/4wb77mDK

**Comment by smolinacadena** [comment]
Having the same issue as well on a multplayer server. Nearly the same crash report about missing Model class def.

**Comment by smolinacadena** [comment]
Here's my crash report if that helps.

Using lastest 1.16.5 forge. 36.2.29

https://pastebin.com/zcSMqSNV

**Comment by VadamDev** [comment]
If I can help you, I created a temporary fix for that issue.
https://github.com/VadamDev/Backpacked/releases/tag/2.1.2-1.16.5

**Comment by MrCrayfish** [comment]
You shouldn't use `@OnlyIn` as it's not intended for modders. I previously used it but removed it. It's all about making sure client code is not run on the server and this crash won't happen. It seems my previous attempt at a fix did not work, I am unable to test since I personally don't have the issue even when running dedicated server.

**Comment by SkullDiamond** [comment]
I could test it if you want 😅

**Comment by smolinacadena** [comment]
Hi @MrCrayfish 

This is the modpack where I was able to reproduce the issue

https://www.curseforge.com/minecraft/modpacks/primatilandia

It's really heavy, needs a minimum of 8GB RAM but could be a starting point to test.

**Comment by VadamDev** [comment]
> I did it just to run the mod on the server side temporarily ^^' . You did you're tests on the development environment or with a "external" server ?
