### ISSUE TITLE
[Suggestion] Item tag for banned items

### ISSUE THREAD

**Issue by MarioSMB** [MrCrayfish/Backpacked#78]
The serverconfig configuration file contains a rather large list of items from various mods that cannot be stored in backpacks.  
This would be much more flexible as an item tag, allowing mod authors and datapack creators to prevent these items from being stored in backpacks.

**Comment by MrCrayfish** [comment]
I thought about this prior to release of 2.0 but this is problem on a larger scale. Adding an item tag would only solve for my own mod, what about other mods that add backpack-esk items? The best solution would be for Forge to add an item tag as a universal solution.

**Comment by MarioSMB** [comment]
Pardon the necro post, but I am just now recalling a thread by the Forge developers stating that support for extra tags doesn't necessarily have to come from them directly; if you were to add a generic tag for items that should be banned from backpacks, other mods may adopt it as a standard.  

Just a thought, it would certainly make things easier for modpack creators!

**Comment by MrCrayfish** [comment]
Now that I think about it, it would be handy for modpack devs. I'll see getting it in the mod soon.
