### ISSUE TITLE
Suggestion for a compat with Curious Shulker Boxes

### ISSUE THREAD

**Issue by SissyTrashQueen** [MrCrayfish/Backpacked#8]
Could the Backpack use the "Back" slot (the [Curious Shulker Box](https://www.curseforge.com/minecraft/mc-mods/curious-shulker-boxes) uses that one) if it recognizes that mod is installed as well, instead of the "Backpacked" slot?

**Comment by MrCrayfish** [comment]
You can change it by overriding it with datapack. The file you need to override is `data/curios/tags/items/backpacked.json` and change the slot definition inside of it to the one from Curios Shulker Boxes.
