### ISSUE TITLE
Backpack enchantment "marksman" doesn't allow gun to grab ammo from bag

### ISSUE THREAD

**Issue by JetpackRescue** [MrCrayfish/Backpacked#83]
Marksman enchantment doesn't use ammo from your backpack. The enchantment doesn't mention bullets, but gun mod is your other mod so I think it should work.

**Comment by MrCrayfish** [comment]
The Gun Mod doesn't use the same search function as a bow does to look for ammo, that's why it doesn't work. It's best you report this on the Gun Mod repo instead of Backpacked.
