### ISSUE TITLE
Looting enchantment doesn't work right if you've changed mob death drops

### ISSUE THREAD

**Issue by JetpackRescue** [MrCrayfish/Backpacked#84]
I changed mob death drops with editmobdrops mod and in control mod, those items don't appear in the backpack and don't drop on the ground with the looting enchantment. I also removed some mob drops like string from spiders, but that IS showing up in the backpack

**Comment by MrCrayfish** [comment]
I've changed the priority of the event that handles capturing the loot drops. Hopefully it should be then compatible with that mod. 9b93825558b0cf106a5a48c7b26d6bcba3600423
