### ISSUE TITLE
[1.16.5 Bug?] Wandering Trader's Backpack has items, not just Emeralds.

### ISSUE THREAD

**Issue by Jusey1** [MrCrayfish/Backpacked#87]
Minecraft: 1.16.5
Forge: 36.2.20
Backpacked: 2.1.2

The config for this seems to imply he would only have emeralds in his backpack, so I assume this is a bug:
![1](https://user-images.githubusercontent.com/61861078/158103364-581aa627-5d42-4107-87a3-4f65209f022f.png)

However, if this is intended... Maybe have a way to limit it only to emeralds? Cause in a modpack which modifies his trades... It can get pretty weird, even causing unstackable items to be fully stacked when they shouldn't be at all.

**Comment by MrCrayfish** [comment]
The items are intentional. The overstacked items are not, I will have a fix soon. Maybe I should add a config option to disable generating items and only allow emeralds?

**Comment by MrCrayfish** [comment]
So I've gone ahead and fixed the overstacked items issue (https://github.com/MrCrayfish/Backpacked/commit/187c34024476a6781247668be4c22fda411ed3f0) and I have also added a config option to generate only emeralds (https://github.com/MrCrayfish/Backpacked/commit/66cc57bab218627780a79cd32b58703f2b422bff). I actually found another bug while investigating this issue.

**Comment by Jusey1** [comment]
Thank you!
