### ISSUE TITLE
Lightfall issue

### ISSUE THREAD

**Issue by VovelPunch** [MrCrayfish/Backpacked#97]
Mohist
lightfall like bungeecord but for mods
issue:
cant connect to server.
[latest.log](https://github.com/MrCrayfish/Backpacked/files/8355093/latest.log)

**Comment by MrCrayfish** [comment]
Bungeecord is notorious for not working with mods. Don't use hybrid software and just use a regular Forge server.

**Comment by VovelPunch** [comment]
wtf your so lazy. And Lazy Forge Servers do NOT USE PLUGINS think before you close an issue that is still an issue!
