### ISSUE TITLE
[1.18.2] release 2.1.3 fails to launch on 40.0.32

### ISSUE THREAD

**Issue by Baggytrousers27** [MrCrayfish/Backpacked#98]
Forge 40.0.32
backpacked-2.1.3-1.18.2

[Debug log](https://pastebin.com/d0UaYG7D)

**Comment by Art1xs** [comment]
Can attest. Seems to be the mod itself.

**Comment by KittenRaee** [comment]
Verified and reproducible.

[crashlog](https://github.com/MrCrayfish/Backpacked/files/8366139/2022-03-28-1.log)

**Comment by MrCrayfish** [comment]
Thnaks for report. I will fix very soon. You can temporarily downgrade to 40.0.15 if you need to play now.

**Comment by MrCrayfish** [comment]
This is resolved now by updating.

**Comment by Baggytrousers27** [comment]
Groovy. ¦D
